### ISSUE TITLE
Damn

### ISSUE THREAD

**Issue by notgoodusename** [Desire2K17/Moonlight#3]
Didnt really think that moonlight would end tbh, hope this gets popular and people stop buying, thanks for giving me credit tho

**Comment by qe7** [comment]
Ur quite welcome, and I too hope people stop buying Moonlight and from Csgopri.me (also owned by 2157) which is just lolz accounts resold for $10 more than lolz.

**Comment by Desire2K17** [comment]
You are very welcome sir

**Comment by kimariga** [comment]
it got me error cant found catchcrackuserbydesire? should i remove it?
