### ISSUE TITLE
Failed to find pattern #8 error

### ISSUE THREAD

**Issue by CherryLunaCupCake** [Desire2K17/Moonlight#7]
get this error after injecting in game Failed to find pattern [#8I](https://cdn.discordapp.com/attachments/1057408391942774836/1058450179868602428/image.png) This the error as you see in the photo, i hope someone can help me fix this error

**Comment by qe7** [comment]
Brother, This source code is 9 Months old and both me and Desire have expressed time after time that we wont work on it, fix it yourself :)
